import LocaleSwitcher from '@/components/LocaleSwitcher';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <LocaleSwitcher />
          <PageTransition>{children}</PageTransition>
      </body>
    </html>
  )
}
